using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using System.IO;
using System.Data.SqlClient;

namespace DangNhap
{
    public partial class frmDTGiangVien : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        Byte[] ImageByArray;
        SqlConnection con = new SqlConnection(@"Data Source=HoangVanVietAnh;Initial Catalog=QuanLyDaoTao;Integrated Security=True");
        public frmDTGiangVien()
        {
            InitializeComponent();
           
            // This line of code is generated by Data Source Configuration Wizard
            giangVien_SelectAllTableAdapter.Fill(qlDaoTaoDataSet.GiangVien_SelectAll);
        }

      

        private void btnThemGV_ItemClick(object sender, ItemClickEventArgs e)
        {
            frmTTGiangVien frmTTGiangVien = new frmTTGiangVien();
            frmTTGiangVien.Show();
            
        }

        private void btnSuaGV_ItemClick(object sender, ItemClickEventArgs e)
        {
            frmTTGiangVien frmTTGiangVien = new frmTTGiangVien();
            frmTTGiangVien.Show();
        }

        private void btnShow_Click(object sender, EventArgs e)
        {
            /*OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "Images(.jpg,.png)|*.png;*.jpg";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                strFilePath = ofd.FileName;
                picGiangVien.Image = new Bitmap(strFilePath);
            }*/
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            /*if (strFilePath == "")
            {
                if (ImageByArray.Length != 0)
                    ImageByArray = new byte[] { };
            }
            else
            {
                Image temp = new Bitmap(strFilePath);
                MemoryStream strm = new MemoryStream();
                temp.Save(strm, System.Drawing.Imaging.ImageFormat.Jpeg);
                ImageByArray = strm.ToArray();
            }
            if (con.State == ConnectionState.Closed)
                con.Open();
            SqlCommand sqlCmd = new SqlCommand("GV_Insert", con) { CommandType = CommandType.StoredProcedure };
            sqlCmd.Parameters.Add("@maGV","GV004");
            sqlCmd.Parameters.Add("@hoTen","Viet Anh");
            sqlCmd.Parameters.Add("@gioiTinh","Nam");
            sqlCmd.Parameters.Add("@diaChi","GoVap HCM");
            sqlCmd.Parameters.Add("@SDT","090909222");
            sqlCmd.Parameters.Add("@ngaySinh","1998/10/7");
            sqlCmd.Parameters.Add("@noiSinh","Hai Duong");
            sqlCmd.Parameters.Add("@trinhDo","Thạc Sỹ");
            sqlCmd.Parameters.Add("@thamNien",3);
            sqlCmd.Parameters.Add("@quyen",2);
            sqlCmd.Parameters.Add("@maKhoa","CNTT");
            sqlCmd.Parameters.Add("@hinh",ImageByArray);
            sqlCmd.Parameters.Add("@email","veitem@gmail.com");
            sqlCmd.ExecuteNonQuery();
            con.Close();
            MessageBox.Show("OK");
            this.Close();
            frmDTGiangVien frmDTGiangVien = new frmDTGiangVien();
            frmDTGiangVien.WindowState = FormWindowState.Maximized;
            frmDTGiangVien.Show();*/
        }

        private void gridVGiangVien_RowCellClick_1(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            laHoTen.Text = gridVGiangVien.Columns.View.GetFocusedRowCellValue("hoTen").ToString();
            byte[] ImageArray = (byte[])gridVGiangVien.Columns.View.GetFocusedRowCellValue("hinh");
            if (ImageArray.Length == 0)
            {
                picGiangVien.Image = null;
            }
            else
            {
                ImageByArray = ImageArray;
                picGiangVien.Image = Image.FromStream(new MemoryStream(ImageArray));
            }
            
        }

        private void frmDTGiangVien_FormClosing(object sender, FormClosingEventArgs e)
        {
            frmDaoTao frmDaoTao = new frmDaoTao();
            frmDaoTao.Show();
        }
    }
}