using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using DevExpress.Data;
using System.IO;

namespace DangNhap
{
    public partial class frmDTSinhVien : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        Byte[] ImageByArray;
        public frmDTSinhVien()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            selectAllSVTableAdapter.Fill(qlDaoTaoDataSetSV.selectAllSV);
            gridCSinhVien.ForceInitialize();
            int count = gridVSinhVien.DataRowCount;
            aceTatCa.Text = "Tất cả (" + count.ToString() + ")";
        }

        private void frmDTSinhVien_FormClosing(object sender, FormClosingEventArgs e)
        {
            frmDaoTao frmDaoTao = new frmDaoTao();
            frmDaoTao.Show();
        }

        private void btnThemSV_ItemClick(object sender, ItemClickEventArgs e)
        {
            this.Close();
            frmTTSinhVien frmTTSinhVien = new frmTTSinhVien();
            frmTTSinhVien.menu("Them");
            frmTTSinhVien.Show();
        }

        private void gridVSinhVien_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            laHoTen.Text = gridVSinhVien.Columns.View.GetFocusedRowCellValue("hoTen").ToString();
            laNganh.Text = gridVSinhVien.Columns.View.GetFocusedRowCellValue("tenNganh").ToString();
            laLop.Text = gridVSinhVien.Columns.View.GetFocusedRowCellValue("tenLop").ToString();
            laSoDT.Text = gridVSinhVien.Columns.View.GetFocusedRowCellValue("SDT").ToString();
            laEmail.Text = gridVSinhVien.Columns.View.GetFocusedRowCellValue("email").ToString();
            byte[] ImageArray = (byte[])gridVSinhVien.Columns.View.GetFocusedRowCellValue("hinh");
            if (ImageArray.Length == 0)
            {
                picSinhVien.Image = null;
            }
            else
            {
                ImageByArray = ImageArray;
                picSinhVien.Image = Image.FromStream(new MemoryStream(ImageArray));
            }
        }

        private void aceTatCa_Click(object sender, EventArgs e)
        {
            coltenKhoa.SortOrder = ColumnSortOrder.None;
            coltenKhoa.GroupIndex = -1;
            coltenLop.SortOrder = ColumnSortOrder.None;
            coltenLop.GroupIndex = -1;
            colgioiTinh.SortOrder = ColumnSortOrder.None;
            colgioiTinh.GroupIndex = -1;
            coltenNganh.SortOrder = ColumnSortOrder.None;
            coltenNganh.GroupIndex = -1;
            colkhoa.SortOrder = ColumnSortOrder.None;
            colkhoa.GroupIndex = -1;
        }

        private void aceLop_Click(object sender, EventArgs e)
        {
            coltenLop.SortOrder = ColumnSortOrder.Ascending;
            coltenLop.GroupIndex = 0;
        }

        private void aceKhoa_Click(object sender, EventArgs e)
        {
            coltenKhoa.SortOrder = ColumnSortOrder.Ascending;
            coltenKhoa.GroupIndex = 0;
        }

        private void aceNganh_Click(object sender, EventArgs e)
        {
            coltenNganh.SortOrder = ColumnSortOrder.Ascending;
            coltenNganh.GroupIndex = 0;
        }

        private void aceKhoaHoc_Click(object sender, EventArgs e)
        {
            colkhoa.SortOrder = ColumnSortOrder.Ascending;
            colkhoa.GroupIndex = 0;
        }

        private void aceGioiTinh_Click(object sender, EventArgs e)
        {
            colgioiTinh.SortOrder = ColumnSortOrder.Ascending;
            colgioiTinh.GroupIndex = 0;
        }

        private void btnSuaSV_ItemClick(object sender, ItemClickEventArgs e)
        {
            String maSV = gridVSinhVien.Columns.View.GetFocusedRowCellValue("maSV").ToString();
            String diaChi = gridVSinhVien.Columns.View.GetFocusedRowCellValue("diaChi").ToString();
            String soDT = gridVSinhVien.Columns.View.GetFocusedRowCellValue("SDT").ToString();
            String gioiTinh = gridVSinhVien.Columns.View.GetFocusedRowCellValue("gioiTinh").ToString();
            String hoTen = gridVSinhVien.Columns.View.GetFocusedRowCellValue("hoTen").ToString();
            //String trinhDo = gridVSinhVien.Columns.View.GetFocusedRowCellValue("trinhDo").ToString();
            String lopHoc = gridVSinhVien.Columns.View.GetFocusedRowCellValue("tenLop").ToString()+" "+ gridVSinhVien.Columns.View.GetFocusedRowCellValue("maLop").ToString();
            String khoa = gridVSinhVien.Columns.View.GetFocusedRowCellValue("khoa").ToString();
            String nganhHoc = gridVSinhVien.Columns.View.GetFocusedRowCellValue("tenNganh").ToString() +" "+ gridVSinhVien.Columns.View.GetFocusedRowCellValue("maNganh").ToString();
            String noiSinh = gridVSinhVien.Columns.View.GetFocusedRowCellValue("noiSinh").ToString();
            String email = gridVSinhVien.Columns.View.GetFocusedRowCellValue("email").ToString();
            String ngaySinh = gridVSinhVien.Columns.View.GetFocusedRowCellValue("ngaySinh").ToString();
            byte[] ImageArray = (byte[])gridVSinhVien.Columns.View.GetFocusedRowCellValue("hinh");
            this.Close();

            /*frmTTSinhVien frmTTSinhVien = new frmTTSinhVien();
            frmTTSinhVien.TTSinhVien(maGV, hoTen, diaChi, soDT, gioiTinh, trinhDo, lopHoc, khoa, email, noiSinh, ngaySinh, ImageArray);
            frmTTSinhVien.menu("Sua");
            frmTTSinhVien.Show();*/

            frmTTSinhVien frmThongTinSV = new frmTTSinhVien();
            frmThongTinSV.TTSinhVien(maSV, hoTen, diaChi, soDT, gioiTinh, lopHoc, nganhHoc,khoa, email, noiSinh, ngaySinh, ImageArray);
            frmThongTinSV.menu("Sua");
            frmThongTinSV.Show();
        }
    }
}